const NS_MESSAGE = 'MESSAGE';

export default {
    CURRENT_ROOM: NS_MESSAGE + '/CURRENT_ROOM',
    HAS_MENU_NEW_MESSAGE: NS_MESSAGE + '/HAS_MENU_NEW_MESSAGE',
    HAS_ROOM_NEW_MESSAGE: NS_MESSAGE + '/HAS_ROOM_NEW_MESSAGE',
    ONLINE_STATUS: NS_MESSAGE + '/ONLINE_STATUS',
    MEMBER: NS_MESSAGE + '/MEMBER',
    MEMBERS: NS_MESSAGE + '/MEMBERS',
    CLEAR_MEMBERS: NS_MESSAGE + '/CLEAR_MEMBERS',
    MESSAGE: NS_MESSAGE + '/MESSAGE',
    MESSAGES: NS_MESSAGE + '/MESSAGES',
    CLEAR_MESSAGES: NS_MESSAGE + '/CLEAR_MESSAGES'
};
