const NS_USER = 'user';

export default {
    USER_AUTHENTICATION: NS_USER + '/AUTHENTICATION',
    USER_PROFILE: NS_USER + '/PROFILE',
    USER_LIST: NS_USER + '/LIST',
    USER_PAGINATION: NS_USER + '/PAGINATION',
    USER_DETAIL: NS_USER + '/DETAIL',
};
