const NS_USER = 'USER';

export default {
    USER_AUTHENTICATION: NS_USER + '/USER_AUTHENTICATION',
    USER_PROFILE: NS_USER + '/PROFILE',
    USER_SIGNIN_MESSAGE: NS_USER + '/SIGNIN_MESSAGE',
    USER_LIST: NS_USER + '/USER_LIST',
    USER_PAGINATION: NS_USER + '/USER_PAGINATION',
    USER_DETAIL: NS_USER + '/USER_DETAIL',
};
