const NS_USER_AUTH = 'USER_AUTH';

export default {
    PROFILE: NS_USER_AUTH + '/PROFILE',
    ACCESS_TOKEN: NS_USER_AUTH + '/ACCESS_TOKEN',
    CLAIMS: NS_USER_AUTH + '/CLAIMS',
    SIGNIN_MESSAGE: NS_USER_AUTH + '/SIGNIN_MESSAGE'
};
