const NS_SOCKET = 'SOCKET';

export default {
    SOCKET_CURRENT_ROOM: NS_SOCKET + '/CURRENT_ROOM',
    SOCKET_HAS_MENU_NEW_MESSAGE: NS_SOCKET + '/HAS_MENU_NEW_MESSAGE',
    SOCKET_HAS_ROOM_NEW_MESSAGE: NS_SOCKET + '/HAS_ROOM_NEW_MESSAGE',
    SOCKET_MEMBER: NS_SOCKET + '/MEMBER',
    SOCKET_MEMBERS: NS_SOCKET + '/MEMBERS',
    SOCKET_CLEAR_MEMBERS: NS_SOCKET + '/CLEAR_MEMBERS',
    SOCKET_MESSAGE: NS_SOCKET + '/MESSAGE',
    SOCKET_MESSAGES: NS_SOCKET + '/MESSAGES',
    SOCKET_CLEAR_MESSAGES: NS_SOCKET + '/CLEAR_MESSAGES',
};
