const NS_SOCKET = 'SOCKET';

export default {
    SOCKET_CURRENT_ROOM: NS_SOCKET + '/CURRENT_ROOM',
    SOCKET_CONTACT: NS_SOCKET + '/CONTACT',
    SOCKET_CONTACTS: NS_SOCKET + '/CONTACTS',
    SOCKET_MESSAGE: NS_SOCKET + '/MESSAGE',
    SOCKET_MESSAGES: NS_SOCKET + '/MESSAGES',
};
