const NS_SOCKET = 'SOCKET';

export default {
    SOCKET_CURRENT_ROOM: NS_SOCKET + '/CURRENT_ROOM',
    SOCKET_HAS_ROOM_NEW_MESSAGE: NS_SOCKET + '/HAS_ROOM_NEW_MESSAGE',
    SOCKET_CONTACT: NS_SOCKET + '/CONTACT',
    SOCKET_CONTACTS: NS_SOCKET + '/CONTACTS',
    SOCKET_CLEAR_CONTACTS: NS_SOCKET + '/CLEAR_CONTACTS',
    SOCKET_MESSAGE: NS_SOCKET + '/MESSAGE',
    SOCKET_MESSAGES: NS_SOCKET + '/MESSAGES',
    SOCKET_CLEAR_MESSAGES: NS_SOCKET + '/CLEAR_MESSAGES',
};
